name: Update Exam Dates

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-dates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Update JSON files with current week dates
      run: |
        python <<EOF
        import json
        from datetime import datetime, timedelta, timezone

        # 设置中国时区（UTC+8）
        china_timezone = timezone(timedelta(hours=8))

        # 计算当周三和周日的日期
        now = datetime.now(china_timezone)
        weekday = now.weekday()  # 0=周一, 1=周二, ..., 6=周日
        current_wednesday = (now + timedelta(days=(2 - weekday))).strftime('%Y-%m-%d')
        current_sunday = (now + timedelta(days=(6 - weekday))).strftime('%Y-%m-%d')

        # 更新 math_exam_config.json 文件（设置为周日日期）
        with open('math_exam_config.json', 'r') as f:
            math_data = json.load(f)

        for exam in math_data['examInfos']:
            exam['start'] = exam['start'].replace(exam['start'][:10], current_sunday)
            exam['end'] = exam['end'].replace(exam['end'][:10], current_sunday)

        with open('math_exam_config.json', 'w') as f:
            json.dump(math_data, f, indent=4, ensure_ascii=False)

        # 更新 physics_exam_config.json 文件（设置为周三日期）
        with open('physics_exam_config.json', 'r') as f:
            physics_data = json.load(f)

        for exam in physics_data['examInfos']:
            exam['start'] = exam['start'].replace(exam['start'][:10], current_wednesday)
            exam['end'] = exam['end'].replace(exam['end'][:10], current_wednesday)

        with open('physics_exam_config.json', 'w') as f:
            json.dump(physics_data, f, indent=4, ensure_ascii=False)
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add math_exam_config.json physics_exam_config.json
        git commit -m "Update math and physics exam dates for the current week"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}